import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Videos belong to a channel, not to a user, and keep the storage key of the
 * original file. Generated by the CLI and completed by hand with the backfill
 * of existing rows: each video moves to its owner's channel (one per user) and
 * gets the key `videos/{id}/source` that the code used to derive.
 */
export class LinkVideosToChannels1791308343731 implements MigrationInterface {
  name = 'LinkVideosToChannels1791308343731';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "videos" ADD "channel_id" uuid`);
    await queryRunner.query(
      `UPDATE "videos" SET "channel_id" = "channels"."id" FROM "channels" WHERE "channels"."user_id" = "videos"."user_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "videos" ALTER COLUMN "channel_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_023a8e4f3f1a34ff3d8ca04a4c" ON "videos" ("channel_id") `,
    );
    await queryRunner.query(
      `ALTER TABLE "videos" ADD CONSTRAINT "FK_023a8e4f3f1a34ff3d8ca04a4cc" FOREIGN KEY ("channel_id") REFERENCES "channels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );

    await queryRunner.query(
      `ALTER TABLE "videos" ADD "source_key" character varying`,
    );
    await queryRunner.query(
      `UPDATE "videos" SET "source_key" = 'videos/' || "id" || '/source'`,
    );
    await queryRunner.query(
      `ALTER TABLE "videos" ALTER COLUMN "source_key" SET NOT NULL`,
    );

    await queryRunner.query(
      `ALTER TABLE "videos" DROP CONSTRAINT "FK_900733992fb36a6d855308c0039"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_900733992fb36a6d855308c003"`,
    );
    await queryRunner.query(`ALTER TABLE "videos" DROP COLUMN "user_id"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "videos" ADD "user_id" uuid`);
    await queryRunner.query(
      `UPDATE "videos" SET "user_id" = "channels"."user_id" FROM "channels" WHERE "channels"."id" = "videos"."channel_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "videos" ALTER COLUMN "user_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_900733992fb36a6d855308c003" ON "videos" ("user_id") `,
    );
    await queryRunner.query(
      `ALTER TABLE "videos" ADD CONSTRAINT "FK_900733992fb36a6d855308c0039" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );

    await queryRunner.query(`ALTER TABLE "videos" DROP COLUMN "source_key"`);

    await queryRunner.query(
      `ALTER TABLE "videos" DROP CONSTRAINT "FK_023a8e4f3f1a34ff3d8ca04a4cc"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_023a8e4f3f1a34ff3d8ca04a4c"`,
    );
    await queryRunner.query(`ALTER TABLE "videos" DROP COLUMN "channel_id"`);
  }
}
